cs:

config:
	git config --list

count:
	ls -al | grep "RunCollatz.in"   | wc -l
	ls -al | grep "RunCollatz.out"  | wc -l
	ls -al | grep "TestCollatz.c++" | wc -l
	ls -al | grep "TestCollatz.py"  | wc -l
	ls -al | grep "TestCollatz.out" | wc -l

log:
	git log

pull:
	git pull

status:
	git branch
	git remote
	git status
